apiVersion: apps/v1
kind: Deployment
metadata:
  name: busapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busapp
  template:
    metadata:
      labels:
        app: busapp
    spec:
      containers:
      - name: busapp
        image: rajijay/busapp:latest
        ports:
        - containerPort: 8080
